### ISSUE TITLE
대시보드 한글화

### ISSUE THREAD

**Issue by kt-cheon** [ablecloud-team/ablestack-wall#2]
#### 이슈 타입

 * 기능 추가 요청
 * 새 기능 아이디어

#### 컴포넌트 이름

~~~

~~~

#### ABLESTACK 버전

~~~
ABLESTACK-Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Wall 대시보드의 영어 메뉴, 타이틀 등을 한글로 변경

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by qoxown12** [comment]
제가 하겠습니다.
