### ISSUE TITLE
대시보드 메뉴 커스터마이징

### ISSUE THREAD

**Issue by kt-cheon** [ablecloud-team/ablestack-wall#3]
#### 이슈 타입

 * 기능 개선 요청

#### 컴포넌트 이름

~~~

~~~

#### ABLESTACK 버전

~~~
ABLESTACK-Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

대시보드의 메뉴를 ABLESTACK에 맞게 커스터마이징 하는 작업이 필요합니다.

#### 재현 과정

upgrade 메뉴 비활성화
HELP 메뉴의 링크를 ABLESTACK Document로 변경

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by qoxown12** [comment]
제가 하겠습니다.
